kind: Service
apiVersion: v1
metadata:
  name: filebin2
  namespace: filebin2
  labels:
    k8s-app: filebin2
  annotations:
    description: filebin2
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: >-
      arn:aws:acm:<region>:<number>:certificate/<uuid>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  selector:
    k8s-app: filebin2
  type: LoadBalancer
  sessionAffinity: None
